/** @type {import('tailwindcss').Config} */

module.exports = {
    important: true,
    corePlugins: {
        preflight: false,
    },
    content: [
        "./**/*.{razor,html}",
        "./wwwroot/**/*.{razor,html}",
        "./DesignComponents/**/*.{razor,html,cs}",
        "../Enable.Design/Forms/*.{razor,cs}",
        "../Enable.Design/Layout/*.{razor,cs}",
        "../Enable.Design/Modal/*.{razor,cs}",
        "../Enable.Design/Grids/**/*.{razor,cs}",
        "../Enable.Design/Filters/*.{razor,cs}",
        "../Enable.Design/Files/*.{razor,cs}",
        "../Enable.Design/Workflow/*.{razor,cs}",
        "../Enable.Design/Tooltips/*.{razor,cs}",
        "../Enable.Design/Accordion/*.{razor,cs}",
        "../Enable.Design/Info/*.{razor,cs}",
        "../Enable.Design/Drawer/*.{razor,cs}",
        "../Enable.Design/Popover/*.{razor,cs}",
        "../Enable.Design/Buttons/*.{razor,cs}"
    ],
    safelist: [
        'w-48', 'w-52', 'w-56', 'w-60', 'w-64',
        'group', 'whitespace-nowrap'
    ],
    theme: {
        screens: {
            'sm': '640px',
            'md': '768px',
            'lg': '1024px',
            'xl': '1280px',
            'xxl': '1281px',
            '1_5xl': '1482px',
            '2xl': '1536px',
            '3xl': '1800px',
            'small': '1280px',
            'medium': '1536px',
            'large': '1920px',
            'ultra': '2560px',
        },
        fontFamily: {
            'enable': 'var(--eds-font-family-normal)'
        },
        fontSize: {
            xs: 'calc(var(--eds-font-size-xs, 0.8125) * 1rem) ',
            sm: 'calc(var(--eds-font-size-s, 1) * 1rem) ',
            md_sm: '1.2rem',
            md: 'calc(var(--eds-font-size-m, 1.5) * 1rem)',
            l: 'calc(var(--eds-font-size-l, 2) * 1rem)',
            xl: 'calc(var(--eds-font-size-xl, 2.75) * 1rem)',
            xxl: 'calc(var(--eds-font-size-xxl, 3) * 1rem)',
            // Body Text Styles
            'body-xs': ['12px', { lineHeight: '14px' }],
            'body-sm': ['14px', { lineHeight: '18px' }],
            'body-md': ['16px', { lineHeight: '20px' }],
            // Button Typography
            'button-sm': ['14px', { lineHeight: '18px' }],
            'button-md': ['16px', { lineHeight: '20px' }],
            // Headings
            h1: ['44px', { lineHeight: '48px' }],
            h2: ['32px', { lineHeight: '32px' }],
            h3: ['24px', { lineHeight: '24px' }],
            h4: ['16px', { lineHeight: '22px' }],
            h5: ['13px', { lineHeight: '22px' }],
        },
        fontWeight: {
            light: 'var(--eds-font-weight-light)',
            normal: 'var(--eds-font-weight-normal)',
            strong: 'var(--eds-font-weight-strong)',
            bold: 'var(--eds-font-weight-bold)',
            extraBold: 'var(--eds-font-weight-xbold)',
            'v2-light': 300,
            'v2-normal': 400,
            'v2-medium': 500,
            'v2-semibold': 600,
            'v2-bold': 700,
            'v2-extrabold': 800,
        },
        colors: {
            'transparent': 'transparent',
            'white': 'var(--eds-color-white)',
            'black': 'var(--eds-color-black)',
            'orange-90': 'var(--eds-color-orange-90)',
            'orange-80': 'var(--eds-color-orange-80)',
            'orange-70': 'var(--eds-color-orange-70)',
            'orange-60': 'var(--eds-color-orange-60)',
            'orange-50': 'var(--eds-color-orange-50)',
            'orange-40': 'var(--eds-color-orange-40)',
            'orange-30': 'var(--eds-color-orange-30)',
            'orange-20': 'var(--eds-color-orange-20)',
            'orange-10': 'var(--eds-color-orange-10)',
            'purple-90': 'var(--eds-color-purple-90)',
            'purple-80': 'var(--eds-color-purple-80)',
            'purple-70': 'var(--eds-color-purple-70)',
            'purple-60': 'var(--eds-color-purple-60)',
            'purple-50': 'var(--eds-color-purple-50)',
            'purple-40': 'var(--eds-color-purple-40)',
            'purple-30': 'var(--eds-color-purple-30)',
            'purple-20': 'var(--eds-color-purple-20)',
            'purple-10': 'var(--eds-color-purple-10)',
            'lime-90': 'var(--eds-color-lime-90)',
            'lime-80': 'var(--eds-color-lime-80)',
            'lime-70': 'var(--eds-color-lime-70)',
            'lime-60': 'var(--eds-color-lime-60)',
            'lime-50': 'var(--eds-color-lime-50)',
            'lime-40': 'var(--eds-color-lime-40)',
            'lime-30': 'var(--eds-color-lime-30)',
            'lime-20': 'var(--eds-color-lime-20)',
            'lime-10': 'var(--eds-color-lime-10)',
            'fuchsia-90': 'var(--eds-color-fuchsia-90)',
            'fuchsia-80': 'var(--eds-color-fuchsia-80)',
            'fuchsia-70': 'var(--eds-color-fuchsia-70)',
            'fuchsia-60': 'var(--eds-color-fuchsia-60)',
            'fuchsia-50': 'var(--eds-color-fuchsia-50)',
            'fuchsia-40': 'var(--eds-color-fuchsia-40)',
            'fuchsia-30': 'var(--eds-color-fuchsia-30)',
            'fuchsia-20': 'var(--eds-color-fuchsia-20)',
            'fuchsia-10': 'var(--eds-color-fuchsia-10)',
            'steel-90': 'var(--eds-color-steel-90)',
            'steel-80': 'var(--eds-color-steel-80)',
            'steel-70': 'var(--eds-color-steel-70)',
            'steel-60': 'var(--eds-color-steel-60)',
            'steel-50': 'var(--eds-color-steel-50)',
            'steel-40': 'var(--eds-color-steel-40)',
            'steel-30': 'var(--eds-color-steel-30)',
            'steel-20': 'var(--eds-color-steel-20)',
            'steel-15': 'var(--eds-color-steel-15)',
            'steel-10': 'var(--eds-color-steel-10)',
            'red-90': 'var(--eds-color-red-90)',
            'red-80': 'var(--eds-color-red-80)',
            'red-70': 'var(--eds-color-red-70)',
            'red-60': 'var(--eds-color-red-60)',
            'red-50': 'var(--eds-color-red-50)',
            'red-40': 'var(--eds-color-red-40)',
            'red-30': 'var(--eds-color-red-30)',
            'red-20': 'var(--eds-color-red-20)',
            'red-10': 'var(--eds-color-red-10)',
            'teal-90': 'var(--eds-color-teal-90)',
            'teal-80': 'var(--eds-color-teal-80)',
            'teal-70': 'var(--eds-color-teal-70)',
            'teal-60': 'var(--eds-color-teal-60)',
            'teal-50': 'var(--eds-color-teal-50)',
            'teal-40': 'var(--eds-color-teal-40)',
            'teal-30': 'var(--eds-color-teal-30)',
            'teal-20': 'var(--eds-color-teal-20)',
            'teal-10': 'var(--eds-color-teal-10)',
            'yellow-90': 'var(--eds-color-yellow-90)',
            'yellow-80': 'var(--eds-color-yellow-80)',
            'yellow-70': 'var(--eds-color-yellow-70)',
            'yellow-60': 'var(--eds-color-yellow-60)',
            'yellow-50': 'var(--eds-color-yellow-50)',
            'yellow-40': 'var(--eds-color-yellow-40)',
            'yellow-30': 'var(--eds-color-yellow-30)',
            'yellow-20': 'var(--eds-color-yellow-20)',
            'yellow-10': 'var(--eds-color-yellow-10)',
            'blue-90': 'var(--eds-color-blue-90)',
            'blue-80': 'var(--eds-color-blue-80)',
            'blue-70': 'var(--eds-color-blue-70)',
            'blue-60': 'var(--eds-color-blue-60)',
            'blue-50': 'var(--eds-color-blue-50)',
            'blue-40': 'var(--eds-color-blue-40)',
            'blue-30': 'var(--eds-color-blue-30)',
            'blue-20': 'var(--eds-color-blue-20)',
            'blue-10': 'var(--eds-color-blue-10)',
            'green-90': 'var(--eds-color-green-90)',
            'green-80': 'var(--eds-color-green-80)',
            'green-70': 'var(--eds-color-green-70)',
            'green-60': 'var(--eds-color-green-60)',
            'green-50': 'var(--eds-color-green-50)',
            'green-40': 'var(--eds-color-green-40)',
            'green-30': 'var(--eds-color-green-30)',
            'green-20': 'var(--eds-color-green-20)',
            'green-10': 'var(--eds-color-green-10)',
            'brand-background-secondary': 'var(--eds-color-steel-10)',
            'brand-background-base': 'var(--eds-color-white)',
            'brand-border-base': 'var(--eds-color-steel-20)',
            'brand-teal-dark': 'var(--eds-color-teal-50)',
            'brand-teal-light': 'var(--eds-color-teal-20)',
            'brand-teal': 'var(--eds-color-teal-30)',
            'brand-yellow-dark': 'var(--eds-color-yellow-30)',
            'brand-yellow-light': 'var(--eds-color-yellow-10)',
            'brand-yellow': 'var(--eds-color-yellow-20)',
            'brand-red-dark': 'var(--eds-color-red-60)',
            'brand-red-light': 'var(--eds-color-red-20)',
            'brand-red': 'var(--eds-color-red-50)',
            'brand-blue-dark': 'var(--eds-color-blue-90)',
            'brand-blue': 'var(--eds-color-blue-80)',
            'brand-blue-light': 'var(--eds-color-blue-60)',
            'brand-green-dark': 'var(--eds-color-green-60)',
            'brand-green': 'var(--eds-color-green-50)',
            'brand-green-light': 'var(--eds-color-green-40)',
            'brand-accent-dark': 'var(--eds-color-blue-90)',
            'brand-accent': 'var(--eds-color-blue-80)',
            'brand-accent-light': 'var(--eds-color-blue-60)',
            'brand-primary-dark': 'var(--eds-color-green-60)',
            'brand-primary': 'var(--eds-color-green-50)',
            'brand-primary-light': 'var(--eds-color-green-40)',
            'brand-status-warning': 'var(--eds-brand-color-status-warning)',
            'brand-status-info': 'var(--eds-brand-color-status-info)',
            //   New tokens based on new designs coming in, please use for all new work.
            "colour-green-10": "var(--brand-green-10)",
            "colour-green-20": "var(--brand-green-20)",
            "colour-green-30": "var(--brand-green-30)",
            "colour-green-40": "var(--brand-green-40)",
            "colour-green-50": "var(--brand-green-50)",
            "colour-green-60": "var(--brand-green-60)",
            "colour-green-70": "var(--brand-green-70)",
            "colour-green-80": "var(--brand-green-80)",
            "colour-green-90": "var(--brand-green-90)",
            "colour-blue-10": "var(--brand-blue-10)",
            "colour-blue-20": "var(--brand-blue-20)",
            "colour-blue-30": "var(--brand-blue-30)",
            "colour-blue-40": "var(--brand-blue-40)",
            "colour-blue-50": "var(--brand-blue-50)",
            "colour-blue-60": "var(--brand-blue-60)",
            "colour-blue-70": "var(--brand-blue-70)",
            "colour-blue-80": "var(--brand-blue-80)",
            "colour-blue-90": "var(--brand-blue-90)",
            "colour-steel-10": "var(--brand-steel-10)",
            "colour-steel-20": "var(--brand-steel-20)",
            "colour-steel-30": "var(--brand-steel-30)",
            "colour-steel-40": "var(--brand-steel-40)",
            "colour-steel-50": "var(--brand-steel-50)",
            "colour-steel-60": "var(--brand-steel-60)",
            "colour-steel-70": "var(--brand-steel-70)",
            "colour-steel-80": "var(--brand-steel-80)",
            "colour-steel-90": "var(--brand-steel-90)",
            "colour-red-10": "var(--brand-red-10)",
            "colour-red-20": "var(--brand-red-20)",
            "colour-red-30": "var(--brand-red-30)",
            "colour-red-40": "var(--brand-red-40)",
            "colour-red-50": "var(--brand-red-50)",
            "colour-red-60": "var(--brand-red-60)",
            "colour-red-70": "var(--brand-red-70)",
            "colour-red-80": "var(--brand-red-80)",
            "colour-red-90": "var(--brand-red-90)",
            "colour-teal-10": "var(--brand-teal-10)",
            "colour-teal-20": "var(--brand-teal-20)",
            "colour-teal-30": "var(--brand-teal-30)",
            "colour-teal-40": "var(--brand-teal-40)",
            "colour-teal-50": "var(--brand-teal-50)",
            "colour-teal-60": "var(--brand-teal-60)",
            "colour-teal-70": "var(--brand-teal-70)",
            "colour-teal-80": "var(--brand-teal-80)",
            "colour-teal-90": "var(--brand-teal-90)",
            "colour-yellow-10": "var(--brand-yellow-10)",
            "colour-yellow-20": "var(--brand-yellow-20)",
            "colour-yellow-30": "var(--brand-yellow-30)",
            "colour-yellow-40": "var(--brand-yellow-40)",
            "colour-yellow-50": "var(--brand-yellow-50)",
            "colour-yellow-60": "var(--brand-yellow-60)",
            "colour-yellow-70": "var(--brand-yellow-70)",
            "colour-yellow-80": "var(--brand-yellow-80)",
            "colour-yellow-90": "var(--brand-yellow-90)",
            "colour-fuchsia-10": "var(--brand-fuchsia-10)",
            "colour-fuchsia-20": "var(--brand-fuchsia-20)",
            "colour-fuchsia-30": "var(--brand-fuchsia-30)",
            "colour-fuchsia-40": "var(--brand-fuchsia-40)",
            "colour-fuchsia-50": "var(--brand-fuchsia-50)",
            "colour-fuchsia-60": "var(--brand-fuchsia-60)",
            "colour-fuchsia-70": "var(--brand-fuchsia-70)",
            "colour-fuchsia-80": "var(--brand-fuchsia-80)",
            "colour-fuchsia-90": "var(--brand-fuchsia-90)",
            "colour-lime-10": "var(--brand-lime-10)",
            "colour-lime-20": "var(--brand-lime-20)",
            "colour-lime-30": "var(--brand-lime-30)",
            "colour-lime-40": "var(--brand-lime-40)",
            "colour-lime-50": "var(--brand-lime-50)",
            "colour-lime-60": "var(--brand-lime-60)",
            "colour-lime-70": "var(--brand-lime-70)",
            "colour-lime-80": "var(--brand-lime-80)",
            "colour-lime-90": "var(--brand-lime-90)",
            "colour-black": "var(--brand-black)",
            "colour-white": "var(--brand-white)",
            "colour-primary-soft": "var(--brand-green-10)",
            "colour-primary-light": "var(--brand-green-50)",
            "colour-primary-base": "var(--brand-green-60)",
            "colour-primary-dark-hover": "var(--brand-green-70)",
            "colour-primary-hard-focus": "var(--brand-green-80)",
            "colour-secondary-soft": "var(--brand-blue-10)",
            "colour-secondary-light": "var(--brand-blue-60)",
            "colour-secondary-base": "var(--brand-blue-70)",
            "colour-secondary-dark-hover": "var(--brand-blue-80)",
            "colour-secondary-hard-focus": "var(--brand-blue-90)",
            "colour-tertiary-soft": "var(--brand-steel-10)",
            "colour-tertiary-light": "var(--brand-steel-20)",
            "colour-tertiary-base": "var(--brand-steel-40)",
            "colour-tertiary-dark-hover": "var(--brand-steel-60)",
            "colour-tertiary-hard-focus": "var(--brand-steel-80)",
            "colour-tertiary-disabled": "var(--brand-steel-30)",
            "colour-contrast-base": "var(--brand-white)",
            "colour-contrast-dark-hover": "var(--brand-blue-20)",
            "colour-contrast-hard-focus": "var(--brand-blue-40)",
            "colour-contrast-disabled": "var(--brand-steel-60)",
            "colour-background-base": "var(--brand-white)",
            "colour-background-secondary": "var(--tertiary-soft)",
            "colour-background-disabled-alt": "var(--tertiary-disabled)",
            "colour-background-inverse": "var(--secondary-dark-hover)",
            "colour-text-base": "var(--brand-black)",
            "colour-text-secondary": "var(--secondary-base)",
            "colour-text-alt-text": "var(--primary-base)",
            "colour-text-disabled-default": "var(--tertiary-base)",
            "colour-text-disabled-alt": "var(--tertiary-dark-hover)",
            "colour-text-active": "var(--brand-green-70)",
            "colour-text-contrast": "var(--brand-white)",
            "colour-text-success": "var(--status-success-base)",
            "colour-text-info": "var(--status-info-base)",
            "colour-text-warning": "var(--status-warning-base)",
            "colour-text-error": "var(--status-error-base)",
            "colour-focus-color": "var(--brand-blue-90)",
            "colour-link-base": "var(--primary-base)",
            "colour-link-hover": "var(--primary-dark-hover)",
            "colour-link-active": "var(--primary-dark-hover)",
            "colour-link-focus": "var(--primary-hard-focus)",
            "colour-link-disabled": "var(--tertiary-disabled)",
            "colour-link-visited": "var(--primary-base)",
            "colour-link-contrast-color": "var(--brand-white)",
            "colour-brand-base": "var(--primary-base)",
            "colour-border-base": "var(--tertiary-light)",
            "colour-border-secondary": "var(--secondary-light)",
            "colour-border-hover": "var(--tertiary-dark-hover)",
            "colour-border-success": "var(--status-success-base)",
            "colour-border-info": "var(--status-info-base)",
            "colour-border-warning": "var(--status-warning-base)",
            "colour-border-error": "var(--status-error-base)",
            "colour-border-contrast": "var(--brand-white)",
            "colour-icon-base-default": "var(--brand-black)",
            "colour-icon-base-alt": "var(--tertiary-dark-hover)",
            "colour-icon-contrast": "var(--brand-white)",
            "colour-icon-primary": "var(--primary-base)",
            "colour-icon-secondary": "var(--secondary-light)",
            "colour-icon-hover": "var(--brand-green-50)",
            "colour-icon-hover-alt": "var(--tertiary-hard-focus)",
            "colour-icon-disabled": "var(--tertiary-disabled)",
            "colour-icon-success": "var(--status-success-base)",
            "colour-icon-info": "var(--status-info-base)",
            "colour-icon-warning": "var(--status-warning-base)",
            "colour-icon-error": "var(--status-error-base)",
            "colour-status-success-soft": "var(--primary-soft)",
            "colour-status-success-light": "var(--primary-light)",
            "colour-status-success-base": "var(--primary-base)",
            "colour-status-success-dark-hover": "var(--primary-dark-hover)",
            "colour-status-success-hard-focus": "var(--primary-hard-focus)",
            "colour-status-info-soft": "var(--secondary-soft)",
            "colour-status-info-light": "var(--secondary-light)",
            "colour-status-info-base": "var(--secondary-base)",
            "colour-status-info-dark-hover": "var(--secondary-dark-hover)",
            "colour-status-info-hard-focus": "var(--secondary-hard-focus)",
            "colour-status-warning-soft": "var(--brand-orange-10)",
            "colour-status-warning-light": "var(--brand-orange-50)",
            "colour-status-warning-base": "var(--brand-orange-60)",
            "colour-status-warning-dark-hover": "var(--brand-orange-70)",
            "colour-status-warning-hard-focus": "var(--brand-orange-80)",
            "colour-status-error-soft": "var(--brand-red-10)",
            "colour-status-error-light": "var(--brand-red-50)",
            "colour-status-error-base": "var(--brand-red-60)",
            "colour-status-error-dark-hover": "var(--brand-red-70)",
            "colour-status-error-hard-focus": "var(--brand-red-80)"
        },
        extend: {}
    },
    plugins: [],
}

