<Project Sdk="Microsoft.NET.Sdk.Razor">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <DisableImplicitNuGetFallbackFolder>true</DisableImplicitNuGetFallbackFolder>
		<NpmLastInstall>node_modules/.last-install</NpmLastInstall>
    </PropertyGroup>


    <ItemGroup>
        <SupportedPlatform Include="browser" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Blazored.Toast" Version="4.2.0" />
        <PackageReference Include="Microsoft.AspNetCore.Components.QuickGrid" Version="8.0.1" />
        <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="8.0.2" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Workflow\" />
      <Folder Include="wwwroot\js\" />
    </ItemGroup>

	<ItemGroup>
		<Watch Include="**/*.scss" />
		<None Update="**/*.css" Watch="false" />
	</ItemGroup>

  <ItemGroup>
    <Content Remove="package.json;package-lock.json" />
    <None Include="package.json;package-lock.json">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
	
	<Target Name="CheckForNpm">
		<Message Importance="high" Text="Checking for NPM..." />
		<Exec Command="npm --version" ContinueOnError="true">
			<Output TaskParameter="ExitCode" PropertyName="ErrorCode" />
		</Exec>
		<Error Condition="'$(ErrorCode)' != '0'" Text="NPM is required to build this project." />
	</Target>

	<Target Name="RunNpmInstall" DependsOnTargets="CheckForNpm" Inputs="package.json" Outputs="$(NpmLastInstall)">
		<Message Importance="high" Text="Running NPM install..." />
		<Exec Command="npm install" />
		<Touch Files="$(NpmLastInstall)" AlwaysCreate="true" />
	</Target>
	
	<Target Name="BuildJS" DependsOnTargets="RunNpmInstall" BeforeTargets="Compile" Inputs="eds.js" Outputs="wwwroot/js/eds.js">
		<Message Importance="high" Text="Building JS..." />
		<Exec Command="npm run build-js" />
	</Target>

	<Target Name="BuildSass" DependsOnTargets="RunNpmInstall" BeforeTargets="Compile" Condition="Exists('Styles/app-fds.scss')" Inputs="Styles/app-fds.scss" Outputs="wwwroot/css/app-fds.css">
		<Message Importance="high" Text="Building Common Sass..." />
		<Exec Command="npm run build-sass" />
	</Target>

	<Target Name="CompileScopedScss" DependsOnTargets="RunNpmInstall" BeforeTargets="Compile">
		<Message Importance="high" Text="Building Component Sass..." />
		<ItemGroup>
			<ScopedScssFiles Include="**/*.razor.scss" />
		</ItemGroup>

		<Exec Command="npx sass -- %(ScopedScssFiles.Identity) %(relativedir)%(filename).css" />
	</Target>
  
</Project>
